# Generated by Django 5.1.6 on 2025-02-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('host', 'Host'), ('customer', 'Customer')], default='guest', max_length=15),
        ),
    ]
