# Generated by Django 5.1.5 on 2025-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customerprofile_user_alter_hostprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='banner',
            field=models.ImageField(null=True, upload_to='users_banner/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users_avatar/'),
        ),
    ]
