# Generated by Django 5.1.6 on 2025-02-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageamenity',
            options={'verbose_name_plural': 'Package amenities'},
        ),
    ]
