# Generated by Django 5.1.6 on 2025-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packageroutepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageroutepoint',
            name='point_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
