# Generated by Django 5.1.6 on 2025-02-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packageroutepoint_point_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
    ]
