# Generated by Django 5.1.6 on 2025-02-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_remove_package_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_image',
        ),
        migrations.AddField(
            model_name='package',
            name='package_image',
            field=models.ManyToManyField(null=True, related_name='Package', to='packages.packageimage'),
        ),
    ]
