# Generated by Django 5.1.6 on 2025-02-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_remove_package_package_image_package_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_image',
        ),
        migrations.AddField(
            model_name='packageimage',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_image', to='packages.package'),
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='package_amenity',
        ),
        migrations.AddField(
            model_name='packagetype',
            name='package_amenity',
            field=models.ManyToManyField(null=True, related_name='Package', to='packages.packageamenity'),
        ),
    ]
