# Generated by Django 5.1.6 on 2025-02-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_remove_package_package_image_packageimage_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageamenity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='icon_name',
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='package_images/'),
        ),
    ]
