# Generated by Django 5.1.6 on 2025-02-26 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_remove_packageamenity_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageAmenity',
            new_name='PackageTypeAmenity',
        ),
        migrations.RemoveField(
            model_name='packagetype',
            name='package_amenity',
        ),
        migrations.AddField(
            model_name='packagetype',
            name='package_type_amenity',
            field=models.ManyToManyField(null=True, related_name='package_type', to='packages.packagetypeamenity'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_type', to='packages.package'),
        ),
    ]
