# Generated by Django 5.1.6 on 2025-02-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_rename_packageamenity_packagetypeamenity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetypeamenity',
            options={'verbose_name_plural': 'Package type amenities'},
        ),
    ]
