# Generated by Django 5.1.6 on 2025-02-26 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_city_options_alter_country_options_and_more'),
        ('packages', '0011_packageamenity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_amenity',
            field=models.ManyToManyField(related_name='package', to='packages.packageamenity'),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to='destinations.destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package', to=settings.AUTH_USER_MODEL),
        ),
    ]
