# Generated by Django 5.1.6 on 2025-02-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_package_package_amenity_alter_package_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='package_type_amenity',
            field=models.ManyToManyField(related_name='package_type', to='packages.packagetypeamenity'),
        ),
    ]
