# Generated by Django 5.1.6 on 2025-02-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_alter_packagetype_package_type_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageroutepoint',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
