# Generated by Django 5.1.6 on 2025-02-26 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0014_packageroutepoint_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageroutepoint',
            name='package',
        ),
        migrations.AddField(
            model_name='packageroutepoint',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='packages.packagetype'),
        ),
    ]
