# Generated by Django 5.1.5 on 2025-02-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0015_remove_packageroutepoint_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_amenity',
        ),
        migrations.DeleteModel(
            name='PackageAmenity',
        ),
    ]
