# Generated by Django 5.1.5 on 2025-02-28 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_remove_package_package_amenity_delete_packageamenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='currency',
        ),
        migrations.CreateModel(
            name='PackageAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_amenity', to='packages.package')),
            ],
            options={
                'verbose_name_plural': 'Package amenities',
            },
        ),
    ]
