# Generated by Django 5.1.5 on 2025-02-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_remove_package_currency_packageamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
