# Generated by Django 5.1.5 on 2025-02-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0018_package_end_date_package_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='package_type_amenity',
            field=models.ManyToManyField(related_name='package_type_amenity', to='packages.packagetypeamenity'),
        ),
    ]
