# Generated by Django 5.1.5 on 2025-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0019_alter_packagetype_package_type_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='package_type_amenity',
            field=models.ManyToManyField(related_name='package_type', to='packages.packagetypeamenity'),
        ),
    ]
