# Generated by Django 5.1.5 on 2025-02-28 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0020_alter_packagetype_package_type_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagetype',
            name='package_type_amenity',
        ),
        migrations.AddField(
            model_name='packagetypeamenity',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_type_amenity', to='packages.packagetype'),
        ),
    ]
