# Generated by Django 5.1.5 on 2025-03-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0021_remove_packagetype_package_type_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageroutepoint',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_route_point', to='packages.packagetype'),
        ),
    ]
