# Generated by Django 4.2.10 on 2025-03-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen')], default='PHP', max_length=20),
        ),
    ]
