# Generated by Django 5.1.6 on 2025-02-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_additionalfees_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalfees',
            old_name='site_fees',
            new_name='site_fees_percent',
        ),
    ]
