# Generated by Django 4.2.10 on 2025-03-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='additional_fees',
        ),
    ]
