# Generated by Django 4.2.10 on 2025-03-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_additional_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_fees',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='transactions.additionalfees'),
            preserve_default=False,
        ),
    ]
