# Generated by Django 4.2.10 on 2025-03-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_additional_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='additional_fees',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='transactions.additionalfees'),
        ),
    ]
