# Generated by Django 4.2.10 on 2025-03-09 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_additional_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagereview',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_review', to='transactions.transaction'),
        ),
    ]
