# Generated by Django 4.2.10 on 2025-03-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_packagereview_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
