# Generated by Django 4.2.10 on 2025-03-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destination_type',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='DestinationType',
        ),
    ]
