# Generated by Django 5.1.6 on 2025-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='added_by_user',
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
